# Generated by Django 4.1.5 on 2023-02-02 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("hor", "Horror"),
                            ("rom", "Romance"),
                            ("adv", "Adventure"),
                            ("fan", "Fantasy"),
                            ("sci", "Science Fiction"),
                            ("non", "Non-fiction"),
                        ],
                        max_length=3,
                    ),
                ),
                ("publication_date", models.DateField()),
                ("isbn", models.CharField(max_length=13, verbose_name="ISBN")),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_books",
                        to="books.author",
                    ),
                ),
            ],
        ),
    ]
