name: Code Quality Tools

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  tests:
    uses: ./.github/workflows/tests.yml